export const GET_ASSET_CATEGORY_DATA = "GET_ASSET_CATEGORY_DATA";
export const SET_ASSET_CATEGORY_DATA = "SET_ASSET_CATEGORY_DATA";
export const ASSET_CATEGORY_FAIL = "ASSET_CATEGORY_FAIL";

export const GET_CHOOSE_ASSET_DATA = "GET_CHOOSE_ASSET_DATA";
export const SET_CHOOSE_ASSET_DATA = "SET_CHOOSE_ASSET_DATA";
export const CHOOSE_ASSET_FAIL = "CHOOSE_ASSET_FAIL";

export const GET_ASSET_TYPE_DATA = "GET_ASSET_TYPE_DATA";
export const SET_ASSET_TYPE_DATA = "SET_ASSET_TYPE_DATA";
export const ASSET_TYPE_FAIL = "ASSET_TYPE_FAIL";
