export const GET_KNOWLEDGE_BASE_TOPIC = "GET_KNOWLEDGE_BASE_TOPIC";
export const SET_KNOWLEDGE_BASE_TOPIC = "SET_KNOWLEDGE_BASE_TOPIC";
export const KNOWLEDGE_BASE_TOPIC_FAIL = "KNOWLEDGE_BASE_FAIL";
