export const GET_KNOWLEDGE_BASE_ARTICLE = "GET_KNOWLEDGE_BASE_ARTICLE";
export const SET_KNOWLEDGE_BASE_ARTICLE = "SET_KNOWLEDGE_BASE_ARTICLE";
export const KNOWLEDGE_BASE_ARTICLE_FAIL = "KNOWLEDGE_BASE_FAIL";
