export const GET_KNOWLEDGE_BASE_TOPIC_ARTICLE =
  "GET_KNOWLEDGE_BASE_TOPIC_ARTICLE";
export const SET_KNOWLEDGE_BASE_TOPIC_ARTICLE =
  "SET_KNOWLEDGE_BASE_TOPIC_ARTICLE";
export const KNOWLEDGE_BASE_TOPIC_ARTICLE_FAIL = "KNOWLEDGE_BASE_FAIL";
