export const GET_LOCATION_DATA = "GET_LOCATION_DATA";
export const SET_LOCATION_DATA = "SET_LOCATION_DATA";
export const LOCATION_DATA_FAIL = "LOCATION_DATA_FAIL";

export const GET_COMPANY_DATA = "GET_COMPANY_DATA";
export const SET_COMPANY_DATA = "SET_COMPANY_DATA";
export const COMPANY_DATA_FAIL = "COMPANY_DATA_FAIL";

export const GET_USER_DATA = "GET_USER_DATA";
export const SET_USER_DATA = "SET_USER_DATA";
export const USER_DATA_FAIL = "USER_DATA_FAIL";
