export const GET_PRIORITY_DATA = "GET_PRIORITY_DATA";
export const SET_PRIORITY_DATA = "SET_PRIORITY_DATA";
export const PRIORITY_DATA_FAIL = "PRIORITY_DATA_FAIL";

export const GET_POST_PRIORITY_DATA = "GET_POST_PRIORITY_DATA";
export const SET_POST_PRIORITY_DATA = "SET_POST_PRIORITY_DATA";
export const POST_PRIORITY_DATA_FAIL = "POST_PRIORITY_DATA_FAIL";
