export const GET_PROFILE_PICTURE_DATA = "GET_PROFILE_PICTURE_DATA";
export const SET_PROFILE_PICTURE_DATA = "SET_PROFILE_PICTURE_DATA";
export const PROFILE_PICTURE_DATA_FAIL = "PROFILE_PICTURE_DATA_FAIL";
