export const GET_PROFILE_DETAILS_DATA = "GET_PROFILE_DETAILS_DATA";
export const SET_PROFILE_DETAILS_DATA = "SET_PROFILE_DETAILS_DATA";
export const PROFILE_DETAILS_FAIL = "PROFILE_DETAILS_DATA_FAIL";
