export const GET_REQUEST_CATEGORY_DATA = "GET_REQUEST_CATEGORY_DATA";
export const SET_REQUEST_CATEGORY_DATA = "SET_REQUEST_CATEGORY_DATA";
export const REQUEST_CATEGORY_FAIL = "REQUEST_CATEGORY_DATA_FAIL";
