export const GET_TICKET_DETAIL_DATA = "GET_TICKET_DETAIL_DATA";
export const SET_TICKET_DETAIL_DATA = "SET_TICKET_DETAIL_DATA";
export const TICKET_DETAIL_DATA_FAIL = "TICKET_DETAIL_DATA_FAIL";

//ticket detail states
export const GET_TICKET_DETAIL_STATE_DATA = "GET_TICKET_DETAIL_STATE_DATA";
export const SET_TICKET_DETAIL_STATE_DATA = "SET_TICKET_DETAIL_STATE_DATA";
export const TICKET_DETAIL_STATE_DATA_FAIL = "TICKET_DETAIL_STATE_DATA_FAIL";
